# Page settings

baseurl = "http://eduardokum.github.io/"
languageCode = "en-us"
title = "Eduardo Gusmão"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Eduardo's Resume"
    author = "Eduardo Gusmão"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Eduardo Gusmão"
        tagline = "Full Stack Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: egc.gusmao@gmail.com"
        title = "egc.gusmao@gmail.com"

        #[[params.contact.list]]
        #class = "phone"
        #icon = "fa-phone"
        #url = "tel:+1234567890"
        #title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//www.eduardogusmao.com.br"
        title = "eduardogusmao.com.br"

        #[[params.contact.list]]
        #class = "linkedin"
        #icon = "fa-linkedin"
        #url = "//linkedin.com/in/johndoe"
        #title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/eduardokum"
        title = "github.com/eduardokum"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/eduardokum"
        title = "@eduardokum"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Major in Information Systems"
        college = "Universidade Bandeirantes"
        dates = "2007 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Portuguese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "intermediary"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Video Games"

        [[params.interests.list]]
        interest = "Cook"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Full Stack Developer**, 10+ year PHP Developer, HTML & CSS & JS, Linux Servers, Databases, Python Developer."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Full Stack Developer"
        dates = "2008 - Present"
        company = "Intrasis, São Paulo"
        details = "Develop maintainable and extensible code in a team environment; formulate and implement plans for development of web applications; setting up the cloud environment, implemented designs, including experimentation and multiple interection."


        [[params.jobs.list]]
        position = "Support Analyst - Internship"
        dates = "2007 - 2008"
        company = "Nesic, São Paulo"
        details = "Resolve help desk issues including troubleshooting hardware and software issues."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**My opensource projects**"

        [[params.projects.list]]
        title = "Laravel Boleto"
        url = "https://github.com/eduardokum/laravel-boleto"
        tagline = "Wrapper of brazilian's payments bills."

        [[params.projects.list]]
        title = "Laravel Mail Auto Embed"
        url = "https://github.com/eduardokum/laravel-mail-auto-embed"
        tagline = "Library to convert img html tags to mail's attachments"

        [[params.projects.list]]
        title = "Correios PHP"
        url = "https://github.com/eduardokum/correios-php"
        tagline = "Library to interact with brazilian's post office."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"


        [[params.skills.list]]
        skill = "PHP & Laravel"
        level = "98%"
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "80%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "85%"

        [[params.skills.list]]
        skill = "Databases"
        level = "85%"


        [[params.skills.list]]
        skill = "Linux Server"
        level = "70%"

        [[params.skills.list]]
        skill = "Python"
        level = "30%"
                

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Eduardo Gusmão"
